### ISSUE TITLE
[css] 技巧

### ISSUE THREAD

**Issue by g770728y** [g770728y/valor-blog#14]
# 子元素marginTop影响父元素
子元素设置marginTop=10
期待父元素上边线 与 子元素上边线 出现10px间距
实际: 父元素跟着子元素下移了10px, 所以间距为0

## 解决
- 父元素 `overflow: hidden`
- 为父元素增加 `border: 1px solid transparent`
- 最好直接使用padding

**Comment by g770728y** [comment]
# 自定义滚动条样式不生效
## 问题
```css
.container::-webkit-scrollbar {
    width: 5px;
}
```
发现滚动条并不是5px, 而是消失了

## 解决
滚动条实际上由: 容器, track, button, thumb, corner 等 组成
上面只定义了容器宽度, 并覆盖了全部默认样式, 所以当前底色为transparent, 自然看不到.
同时定义一下thumb就行了
```css
.container::-webkit-scrollbar {
  width: 5px;
  background: #ccc;
}
.container::-webkit-scrollbar-thumb {
   background: #333;
   box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
   border-radius: 3px;
}
```

**Comment by g770728y** [comment]
# 希望将滚动条放在左侧
## 问题
为了美观, 有时需要将滚动条放在左侧.

## 解决
利用`direction`属性:
```css
.parentWrapper {
    overflow-y: auto;
    direction: rtl;      // 让滚动条放在左侧
}
.parent {
    direction: ltr;    // 让内容仍然从左到右
}
```
